- "{{ .global.hwameistorImageRegistry}}/{{ .scheduler.imageRepository}}:{{ .scheduler.tag}}"
- "{{ .global.hwameistorImageRegistry }}/{{ .admission.imageRepository }}:{{ .admission.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .evictor.imageRepository }}:{{ .evictor.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManager.csi.registrar.imageRepository }}:{{ .localDiskManager.csi.registrar.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .localDiskManager.manager.imageRepository }}:{{ .localDiskManager.manager.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManager.csi.provisioner.imageRepository }}:{{ .localDiskManager.csi.provisioner.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManager.csi.attacher.imageRepository }}:{{ .localDiskManager.csi.attacher.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.registrar.imageRepository }}:{{ .localStorage.csi.registrar.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .localStorage.member.imageRepository }}:{{ .localStorage.member.tag }}"
- "{{ .localStorage.migrate.rclone.imageRepository }}:{{ .localStorage.migrate.rclone.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.provisioner.imageRepository }}:{{ .localStorage.csi.provisioner.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.attacher.imageRepository }}:{{ .localStorage.csi.attacher.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.resizer.imageRepository }}:{{ .localStorage.csi.resizer.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.monitor.imageRepository }}:{{ .localStorage.csi.monitor.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.snapshotController.imageRepository }}:{{ .localStorage.csi.snapshotController.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.csi.snapshotter.imageRepository }}:{{ .localStorage.csi.snapshotter.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .apiserver.imageRepository }}:{{ .apiserver.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .exporter.imageRepository }}:{{ .exporter.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .auditor.imageRepository }}:{{ .auditor.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .failoverAssistant.imageRepository }}:{{ .failoverAssistant.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .pvcAutoResizer.imageRepository }}:{{ .pvcAutoResizer.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .localDiskActionController.imageRepository }}:{{ .localDiskActionController.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ui.imageRepository }}:{{ .ui.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .operator.imageRepository }}:{{ .operator.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .preHookJob.imageRepository }}:{{ .preHookJob.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-shipper:{{ .ha.drbdVersion }}_v0.3.6"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-rhel7:{{ .ha.drbdVersion }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-rhel8:{{ .ha.drbdVersion }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-rhel9:{{ .ha.drbdVersion }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-kylin10:{{ .ha.drbdVersion }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-bionic:{{ .ha.drbdVersion }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-focal:{{ .ha.drbdVersion }}"
# - "{{ .global.hwameistorImageRegistry }}/{{ .ha.imageRepoOwner }}/drbd9-jammy:v9.1.11"
